### ISSUE TITLE
[Windows] Runtimes bin directory must be in Path

### ISSUE THREAD

**Issue by award999** [swiftlang/swift-installer-scripts#303]
When doing some testing of vscode-swift, realized if the runtimes bin directory at `<user dir>\AppData\Local\Programs\Swift\Runtimes\6.0.0\usr\bin\` is not in your path then you cannot run the fully resolved path to swift.exe `<user dir>\AppData\Local\Programs\Swift\Toolchains\6.0.0+Asserts\usr\bin\swift.exe` which I had set in vscode-swift extension. There was no output from the process so took a long time to figure out what the issue even was. Not sure if there is anything we can do here to relatively find this path when running swift.exe? Not 100% sure how I got in this state to begin with, but can reproduce by removing the Runtimes bin directory from the Path

**Comment by compnerd** [comment]
This sounds like something went wrong with your install or you changed your system. The installer already adjusts the path: https://github.com/swiftlang/swift-installer-scripts/blob/main/platforms/Windows/rtl/msi/rtlmsi.wxs#L19-L23
