### ISSUE TITLE
InternalCollectionUtilities.dll missing

### ISSUE THREAD

**Issue by dschaefer2** [swiftlang/swift-installer-scripts#318]
With both the arm64 and x86_64 installs from the July 27'th toolchain, running `swift build` produces an error with the InternalCollectionsUtilities.dll missing from the install.

I'll assume that because the build succeeded that the DLL does exist but just isn't packaged.

The Dependencies utility shows me it's from the Workspace module in swiftpm. But not obvious looking at the source how it gets there.

**Comment by dschaefer2** [comment]
Also included from other modules in swiftpm.

**Comment by compnerd** [comment]
CC: @shahmishal - we should figure out how to get some smoke tests going for the nightlies.

**Comment by shahmishal** [comment]
@compnerd can you share details on running smoke test on Windows?

**Comment by dschaefer2** [comment]
In this case simply running a swift package init failed as well. Creating an executable package, building and running it and make sure Hello World came out would ensure a minimum sanity for swiftpm and the compiler.
