### ISSUE TITLE
ARM64 fails to load package manifests

### ISSUE THREAD

**Issue by dschaefer2** [swiftlang/swift-installer-scripts#326]
I'm not sure how the toolchain picks up these libs but I'll start here.

I am getting the following link error when SwiftPM tries to build the package manifest. It works fine with the x86_64 toolchain, but not with ARM64.

lld-link: error: could not open 'msvcrt.lib': no such file or directory
lld-link: error: could not open 'oldnames.lib': no such file or directory
lld-link: error: could not open 'msvcprt.lib': no such file or directory
lld-link: error: could not open 'legacy_stdio_definitions.lib': no such file or directory

**Comment by shahmishal** [comment]
cc: @compnerd

**Comment by compnerd** [comment]
This is the wrong place to report that issue - we do not have any native components in the installer. It seems like a user error though - those files are provided by VS. Did you install the native ARM64 VS and the native ARM64 toolchain?

**Comment by compnerd** [comment]
@shahmishal should we move this to swiftlang/swift?

**Comment by compnerd** [comment]
@dschaefer2 - software, just work? Wouldn't that be the day?

**Comment by dschaefer2** [comment]
Indeed :). Closing this one.
